# syntax=docker/dockerfile:1

FROM mcr.microsoft.com/dotnet/sdk:8.0-alpine AS build
WORKDIR /src

COPY ./MiniTwitAPI/MiniTwitAPI.csproj ./
RUN dotnet restore

COPY . .
RUN dotnet publish ./MiniTwitAPI/MiniTwitAPI.csproj -c Release -o /app/publish /p:UseAppHost=false

FROM mcr.microsoft.com/dotnet/aspnet:8.0-alpine AS final
WORKDIR /app

RUN apk add --no-cache icu-libs tzdata

ENV ASPNETCORE_URLS=http://+:8080 \
    DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=false

RUN addgroup -S app && adduser -S app -G app
USER app

COPY --from=build /app/publish ./

EXPOSE 8080
ENTRYPOINT ["dotnet", "MiniTwitAPI/MiniTwitAPI.dll"]
