version: '3.3'

networks:
  main:

services:
  minitwitimage:
    image: ${DOCKER_USERNAME}/minitwitimage
    container_name: minitwit
    networks:
      - main
    ports:
      - '8080:8080'
    environment:
      - SpecialApp__AuthorizationHeader=c2ltdWxhdG9yOnN1cGVyX3NhZmUh
      - ASPNETCORE_ENVIRONMENT=prod
      - ConnectionStrings__DefaultConnection=Server=minitwit-db-do-user-19193573-0.i.db.ondigitalocean.com;Port=25060;Database=defaultdb;Uid=doadmin;Pwd=AVNS_HlleQVNYchp5TcN-Ay_;SslMode=Required;
    restart: always
