version: '3.3'

networks:
  main:

services:
  minitwitimage:
    image: ${DOCKER_USERNAME}/minitwitimage
    container_name: minitwit
    depends_on: 
      - itusqlimage
    networks:
      - main
    ports:
      - '5000:5000'
