---
name: Continuous Deployment

on:
  push:
    # Run workflow every time something is pushed to the main branch
    branches:
      - main
      - master

# Remember to set the following secrets in your repository's settings:
# https://github.com/your_username/itu-minitwit-ci/settings/secrets/actions
# DOCKER_USERNAME
# DOCKER_PASSWORD
# DROPLET_USER
# DROPLET_SSH_KEY
# DROPLET_IP

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push minitwitimage
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile-minitwit
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/minitwitimage:latest
          cache-from: type=registry,ref=${{ secrets.DOCKER_USERNAME }}/minitwitimage:webbuildcache
          cache-to: type=registry,ref=${{ secrets.DOCKER_USERNAME }}/minitwitimage:webbuildcache,mode=max

      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh/
          echo "$DROPLET_SSH_KEY" > ~/.ssh/do_DROPLET_SSH_KEY
          chmod 600 ~/.ssh/do_DROPLET_SSH_KEY
        env:
          DROPLET_SSH_KEY: ${{ secrets.DROPLET_SSH_KEY }}
      
      - name: Upload remote_files to server
        env:
          DROPLET_USER: ${{ secrets.DROPLET_USER }}
          DROPLET_IP: ${{ secrets.DROPLET_IP }}
        run: |
          set -e
          if [ -z "$DROPLET_USER" ] || [ -z "$DROPLET_IP" ]; then
            echo "DROPLET_USER/DROPLET_IP not set (check repo Secrets or Environment)."; exit 1
          fi
          ssh -i ~/.ssh/do_DROPLET_SSH_KEY -o StrictHostKeyChecking=no "$DROPLET_USER@$DROPLET_IP" "mkdir -p /minitwit"
          rsync -az --delete -e "ssh -i ~/.ssh/do_DROPLET_SSH_KEY -o StrictHostKeyChecking=no" \
            remote_files/ "$DROPLET_USER@$DROPLET_IP:/minitwit/"
      
      - name: Deploy to server
        env:
          DROPLET_USER: ${{ secrets.DROPLET_USER }}
          DROPLET_IP: ${{ secrets.DROPLET_IP }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          ssh -i ~/.ssh/do_DROPLET_SSH_KEY -o StrictHostKeyChecking=no "$DROPLET_USER@$DROPLET_IP" \
            "chmod +x /minitwit/deploy.sh && DOCKER_USERNAME='$DOCKER_USERNAME' DOCKER_PASSWORD='$DOCKER_PASSWORD' /minitwit/deploy.sh"
